name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - run: pnpm install --filter ./packages/webapp

      - name: Compile Paraglide
        run: pnpm run --filter ./packages/webapp compile-paraglide

      - name: Run tests
        run: pnpm run --filter ./packages/webapp test

      - name: Build webapp
        run: pnpm run --filter ./packages/webapp build

      - name: Copy 404.html
        run: cp ./packages/webapp/dist/index.html ./packages/webapp/dist/404.html

      - name: Create CNAME file
        if: "${{ vars.CNAME != '' }}"
        run: echo "${{ vars.CNAME }}" > ./packages/webapp/dist/CNAME

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/webapp/dist
          force_orphan: true
